# Generated by Django 4.0.3 on 2022-05-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('1', 'OS'), ('2', 'Mobile Application'), ('3', 'GPU & CPU')], max_length=150, null=True),
        ),
    ]
