# Generated by Django 4.0.3 on 2022-04-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
