# Generated by Django 4.0.3 on 2022-04-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_attend_age_attend_gender_attend_governorates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='education',
            field=models.CharField(choices=[('IS', 'متوسطة'), ('HS', 'اعدادية'), ('DIP', 'دبلوم'), ('BAC', 'بكلوريوس'), ('MD', 'ماجستير'), ('DOC', 'دكتوراه'), ('OTH', 'اخرى')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='attend',
            name='specialty',
            field=models.CharField(choices=[('MD', 'طبية'), ('ENG', 'هندسية'), ('SCI', 'العلوم'), ('FE', 'كلية التربية'), ('IN', 'معهد'), ('S', 'طالب اعدادية'), ('OTH', 'اخرى')], max_length=3, null=True),
        ),
    ]
