# Generated by Django 4.0.3 on 2022-04-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='about',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
